### ISSUE TITLE
Missing Event.persist()

### ISSUE THREAD

**Issue by andylamax** [Kotlin/kotlinx-browser#1]
Although an easy work around van be provided, it's nice if this can be incorporated in the defined external Event class

**Comment by trilis** [comment]
Hi! I don't see this method here: https://developer.mozilla.org/en-US/docs/Web/API/Event. Do you mean React one? Please note that React is not supported in this library at the moment.

**Comment by andylamax** [comment]
Got it

**Comment by igoriakovlev** [comment]
This MR is closed because of this repository is now used for Kotlin WasmJs implementation. The Kotlin JS platform implementation we have no plans to yet.
