### ISSUE TITLE
Use @OptIn(ExperimentalContracts::class) instead of @ExperimentalContracts on createElement funs in Builders.kt

### ISSUE THREAD

**Issue by bashor** [Kotlin/kotlinx-browser#11]
Otherwise, every user of `createElement` needs to put OptIn on their side.

**Comment by bashor** [comment]
https://github.com/Kotlin/kotlinx-browser/blob/dfbdceed314567983c98f1d66e8c2e10d99c5a55/src/wasmJsMain/kotlin/kotlinx/dom/Builders.kt#L17-L21

**Comment by igoriakovlev** [comment]
Fixed
