### ISSUE TITLE
Is this project still relevant?

### ISSUE THREAD

**Issue by joffrey-bion** [Kotlin/kotlinx-browser#9]
Given the absence of updates for years, it looks like the browser APIs are in the stdlib and not brought by this module anymore.

Is this the case? If yes, maybe this project should be archived?

I'm trying to figure out why the `dom` package is not found in my project, and I struggle to find information about which of `dom.html` or `org.w3c.html` or `kotlinx.browser` or other packages I am supposed to use. This project adds to the confusion.

**Comment by trilis** [comment]
Right, this repo probably hasn't been relevant for a long time. @bashor can you please confirm and archive it?

**Comment by ilya-g** [comment]
We still have plans to extract `org.w3c` and `kotlinx.dom`/`browser` packages from stdlib-js in the near future, and this repository will likely be used for that.

**Comment by bashor** [comment]
I'd suggest to write relevant infroamtion to README.md and arhive the repo now.
cc @anton-bannykh @ilgonmic

**Comment by igoriakovlev** [comment]
This MR is closed because of this repository is now used for Kotlin WasmJs implementation. The Kotlin JS platform implementation we have no plans to yet.
